[[nodes]]
node_id = 0
endpoint = "172.28.0.10:7000"
neighbors = [1]

[[nodes]]
node_id = 1
endpoint = "172.28.0.11:7000"
neighbors = [0, 2]

[[nodes]]
node_id = 2
endpoint = "172.28.0.12:7000"
neighbors = [1, 3]

[[nodes]]
node_id = 3
endpoint = "172.28.0.13:7000"
neighbors = [2]

